apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-server
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi 
  volumeName: prometheus-pv-server # Corrected storage request value
  storageClassName: gp2  # Ensure no extra spaces here

